//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanningDbContext : DbContext
    {
        public PlanningDbContext()
            : base("name=PlanningDbContext")
        {
        }
    

        public PlanningDbContext(string connectionString)
            :base(connectionString)
        {

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DelayReason> DelayReasons { get; set; }
        public virtual DbSet<Depositor> Depositors { get; set; }
        public virtual DbSet<Gateway> Gateways { get; set; }
        public virtual DbSet<OperType> OperTypes { get; set; }
        public virtual DbSet<ShipmentOrder> ShipmentOrders { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<LvAttr> LvAttr { get; set; }
        public virtual DbSet<ShipmentElement> ShipmentElements { get; set; }
    }
}
