//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanningDbContext : DbContext
    {
        public PlanningDbContext()
            : base("name=PlanningDbContext")
        {
        }
    
    	 public PlanningDbContext(string connectionString)
            : base(connectionString)
        {
    	}
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DelayReason> DelayReasons { get; set; }
        public virtual DbSet<Depositor> Depositors { get; set; }
        public virtual DbSet<Gateway> Gateways { get; set; }
        public virtual DbSet<OperType> OperTypes { get; set; }
        public virtual DbSet<ShipmentOrder> ShipmentOrders { get; set; }
        public virtual DbSet<Shipment> Shipments { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<LvAttr> LvAttrs { get; set; }
        public virtual DbSet<ShipmentElement> ShipmentElements { get; set; }
        public virtual DbSet<TransportCompany> TransportCompanies { get; set; }
        public virtual DbSet<TransportType> TransportTypes { get; set; }
        public virtual DbSet<UserGrpPrvlg> UserGrpPrvlgs { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<Movement> Movements { get; set; }
        public virtual DbSet<MovementItem> MovementItems { get; set; }
    }
}
