//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class delivery_period
    {
        public int id { get; set; }
        public Nullable<int> custom_post_id { get; set; }
        public Nullable<int> warehouse_id { get; set; }
        public Nullable<int> delivery_day { get; set; }
    
        public virtual custom_posts custom_posts { get; set; }
        public virtual warehouses warehouses { get; set; }
    }
}
