//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvAttr
    {
        public int Id { get; set; }
        public Nullable<int> SheId { get; set; }
        public Nullable<bool> LvaIn { get; set; }
        public Nullable<int> LvaAttrLvId { get; set; }
        public Nullable<bool> LvaUseOrdAttr { get; set; }
        public string LvaDB { get; set; }
        public string LvaField { get; set; }
        public Nullable<int> PlDepId { get; set; }
        public Nullable<int> PlElemId { get; set; }
    }
}
