//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class LvAttr
    {
        public int Id { get; set; }
        public Nullable<bool> LvaIn { get; set; }
        public Nullable<int> LvaAttrLvId { get; set; }
        public Nullable<bool> LvaUseOrdAttr { get; set; }
        public string LvaDB { get; set; }
        public string LvaField { get; set; }
        public Nullable<int> PlDepId { get; set; }
        public Nullable<int> PlElemId { get; set; }
    }
}
