//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementItemLog
    {
        public int DmlId { get; set; }
        public string DmlType { get; set; }
        public System.DateTime DmlDate { get; set; }
        public string DmlUserName { get; set; }
        public string DmlCompName { get; set; }
        public int MovementItemId { get; set; }
        public int MovementId { get; set; }
        public int DepositorId { get; set; }
        public int TklLVID { get; set; }
    }
}
