//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovementItem
    {
        public int Id { get; set; }
        public int MovementId { get; set; }
        public int DepositorId { get; set; }
        public int TklLVID { get; set; }
    
        public virtual Depositor Depositors { get; set; }
        public virtual Movement Movement { get; set; }
    }
}
