//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shipment()
        {
            this.ShipmentOrders = new HashSet<ShipmentOrder>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LvId { get; set; }
        public Nullable<int> TimeSlotId { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string SComment { get; set; }
        public string OComment { get; set; }
        public Nullable<int> GateId { get; set; }
        public Nullable<bool> SpCondition { get; set; }
        public string DriverPhone { get; set; }
        public string DriverFio { get; set; }
        public string VehicleNumber { get; set; }
        public string TrailerNumber { get; set; }
        public string AttorneyNumber { get; set; }
        public Nullable<System.DateTime> AttorneyDate { get; set; }
        public Nullable<System.DateTime> SubmissionTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<int> DelayReasonsId { get; set; }
        public string DelayComment { get; set; }
        public Nullable<int> DepositorId { get; set; }
        public Nullable<bool> IsCourier { get; set; }
        public string ForwarderFio { get; set; }
        public string StampNumber { get; set; }
        public string AttorneyIssued { get; set; }
        public Nullable<bool> ShIn { get; set; }
        public Nullable<System.TimeSpan> SpecialTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public Nullable<bool> IsAddLv { get; set; }
        public Nullable<int> TransportCompanyId { get; set; }
        public Nullable<int> TransportTypeId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> CustomPostId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> TransportViewId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShipmentOrder> ShipmentOrders { get; set; }
        public virtual DelayReason DelayReason { get; set; }
        public virtual Depositor Depositor { get; set; }
        public virtual Gateway Gateway { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual TransportCompany TransportCompanies { get; set; }
        public virtual TransportType TransportTypes { get; set; }
        public virtual Supplier suppliers { get; set; }
        public virtual CustomPost custom_posts { get; set; }
        public virtual TransportView transport_view { get; set; }
        public virtual Warehouse warehouses { get; set; }
    }
}
