//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentOrder
    {
        public int Id { get; set; }
        public string OrderId { get; set; }
        public Nullable<int> ShipmentId { get; set; }
        public string OrderType { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsBinding { get; set; }
        public Nullable<int> ManualLoad { get; set; }
        public Nullable<int> ManualUnload { get; set; }
        public Nullable<int> PalletAmount { get; set; }
        public Nullable<int> BindingId { get; set; }
        public Nullable<int> LVOrderId { get; set; }
        public string lv_order_code { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
