//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentsLog
    {
        public int DmlId { get; set; }
        public string DmlType { get; set; }
        public System.DateTime DmlDate { get; set; }
        public string DmlUserName { get; set; }
        public string DmlCompName { get; set; }
        public int ShipmentId { get; set; }
        public Nullable<int> LvId { get; set; }
        public Nullable<int> TimeSlotId { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public string SComment { get; set; }
        public string OComment { get; set; }
        public Nullable<int> GateId { get; set; }
        public Nullable<bool> SpCondition { get; set; }
        public string DriverPhone { get; set; }
        public string DriverFio { get; set; }
        public string VehicleNumber { get; set; }
        public string TrailerNumber { get; set; }
        public string AttorneyNumber { get; set; }
        public Nullable<System.DateTime> AttorneyDate { get; set; }
        public Nullable<System.DateTime> SubmissionTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
        public Nullable<int> DelayReasonsId { get; set; }
        public string DelayComment { get; set; }
        public Nullable<int> DepositorId { get; set; }
        public Nullable<bool> IsCourier { get; set; }
        public string ForwarderFio { get; set; }
        public string StampNumber { get; set; }
        public string AttorneyIssued { get; set; }
        public Nullable<bool> SIn { get; set; }
        public Nullable<System.TimeSpan> SpecialTime { get; set; }
        public Nullable<bool> IsAddLv { get; set; }
        public Nullable<int> TransportCompanyId { get; set; }
        public Nullable<int> TransportTypeId { get; set; }
    }
}
