//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentOrderPart
    {
        public int Id { get; set; }
        public Nullable<int> ShOrderId { get; set; }
        public Nullable<int> OsLvId { get; set; }
        public string OsLvCode { get; set; }
        public Nullable<bool> IsBinding { get; set; }
        public Nullable<int> ManualLoad { get; set; }
        public Nullable<int> ManualUnload { get; set; }
        public Nullable<int> PalletAmount { get; set; }
        public Nullable<int> ShippingPlacesNumber { get; set; }
        public Nullable<decimal> OrderPartWeight { get; set; }
    
        public virtual ShipmentOrder ShipmentOrder { get; set; }
    }
}
