//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planning
{
    using System;
    using System.Collections.Generic;
    
    public partial class VShipments
    {
        public Nullable<int> LvId { get; set; }
        public Nullable<int> OperType { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<int> Klient { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> PrcReady { get; set; }
        public string SComment { get; set; }
        public string OComment { get; set; }
        public Nullable<int> GateName { get; set; }
        public Nullable<bool> SpCondition { get; set; }
        public string DriverPhone { get; set; }
        public string DriverFio { get; set; }
        public Nullable<int> TransportCompany { get; set; }
        public string VehicleNumber { get; set; }
        public string TrailerNumber { get; set; }
        public string AttorneyNumber { get; set; }
        public Nullable<System.DateTime> AttorneyDate { get; set; }
        public Nullable<System.DateTime> SubmissionTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTimePlan { get; set; }
        public Nullable<System.DateTime> EndTimeFact { get; set; }
        public string DelayReasonName { get; set; }
        public string DelayComment { get; set; }
        public string ForwarderFio { get; set; }
        public string TimeSlotName { get; set; }
        public Nullable<System.DateTime> SDate { get; set; }
        public int ShpId { get; set; }
        public Nullable<bool> SIn { get; set; }
        public Nullable<int> DepLvId { get; set; }
        public string DepLvDb { get; set; }
        public Nullable<int> time_slot_id { get; set; }
        public Nullable<int> gate_id { get; set; }
        public Nullable<bool> is_courier { get; set; }
        public Nullable<int> dep_id { get; set; }
        public string dep_name { get; set; }
    }
}
