insert into shipment_element (field_name, field_db_name, field_type) values('Дата','s_date',3)
insert into shipment_element (field_name, field_db_name, field_type) values('Комментарий к погрузке','s_comment',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Ворота','gate_name',2)
insert into shipment_element (field_name, field_db_name, field_type) values('Тайм слот','slot_time',4)
insert into shipment_element (field_name, field_db_name, field_type) values('Курьерская служба','is_courier',5)
insert into shipment_element (field_name, field_db_name, field_type) values('Причина опоздания','delay_reason_name',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Комментарий к опозданию','delay_comment',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Время подачи документов','submission_time',4)
insert into shipment_element (field_name, field_db_name, field_type) values('Время начала','start_time',4)
insert into shipment_element (field_name, field_db_name, field_type) values('Время окончания','end_time',4)
insert into shipment_element (field_name, field_db_name, field_type) values('Убытие по факту','leave_time',4)
insert into shipment_element (field_name, field_db_name, field_type) values('Ф.И.О. водителя','driver_fio',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Телефон водителя','driver_phone',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Ф.И.О. экспедитора','forwarder_fio',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Номер ТС','vehicle_number',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Номер прицепа','trailer_number',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Пломба','stamp_number',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Номер доверенности','attorney_number',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Дата доверенности','attorney_date',3)
insert into shipment_element (field_name, field_db_name, field_type) values('Кем выдана доверенность','attorney_issued',1)
insert into shipment_element (field_name, field_db_name, field_type) values('Спец. условия','sp_condition',5)
